### ISSUE TITLE
Pelican github action

### ISSUE THREAD

**Issue by craig-shenton** [nhs-pycom/dev-nhs.pycom#1]
@suesdesign The [Pelican github action](https://github.com/marketplace/actions/github-pages-pelican-build-action) is now working, but only seems to build the [blog website](https://nhs-pycom.github.io/dev-nhs.pycom/blog/). Not sure if there is a specific command you are using to build all pages from `content/`?

**Comment by suesdesign** [comment]
The command to build is pelican content -s publishconf.py. I will add this to the README file when I create that later.
